language: node_js
node_js: '0.12'
script:
  - gulp remote:$TEST
sudo: false
cache:
  directories:
    - node_modules
env:
  matrix:
    - TEST=unit-mac-chrome
    - TEST=unit-mac-firefox
    - TEST=unit-mac-safari
    - TEST=unit-windows-chrome
    - TEST=unit-windows-firefox
    - TEST=unit-windows-ms-edge
    - TEST=unit-windows-ie-11
    - TEST=unit-linux-chrome
    - TEST=unit-linux-firefox
    - TEST=unit-ipad
    - TEST=unit-iphone
    - TEST=unit-android
